# Generated by Django 5.2.4 on 2025-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='contactwithme',
            options={'verbose_name_plural': 'Contact With Me'},
        ),
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name_plural': 'Image Gallery'},
        ),
        migrations.AlterModelOptions(
            name='setuppage',
            options={'verbose_name_plural': 'Setup Page'},
        ),
        migrations.AddField(
            model_name='setuppage',
            name='locaion_on_map',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setuppage',
            name='location',
            field=models.TextField(),
        ),
    ]
