# Generated by Django 5.2.4 on 2025-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0002_videogallery_alter_aboutme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='myQRcode',
            field=models.ImageField(blank=True, null=True, upload_to='aboutme/myQRcode/'),
        ),
    ]
