# Generated by Django 5.2.4 on 2025-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0003_aboutme_myqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuppage',
            name='page_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
