# Generated by Django 5.2.4 on 2025-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0004_setuppage_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='image_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
