# Generated by Django 5.2.4 on 2025-07-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0005_imagegallery_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='mobile',
        ),
    ]
