# Generated by Django 5.2.4 on 2025-07-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0006_rename_subject_message_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuppage',
            name='image_of_location_icon',
            field=models.ImageField(blank=True, null=True, upload_to='contctWithMe/icon/'),
        ),
        migrations.AddField(
            model_name='setuppage',
            name='image_of_mobile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='contctWithMe/icon/'),
        ),
        migrations.AddField(
            model_name='setuppage',
            name='share_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
