# Generated by Django 5.2.4 on 2025-07-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0007_setuppage_image_of_location_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setuppage',
            old_name='locaion_on_map',
            new_name='location_on_map',
        ),
    ]
