# Generated by Django 5.2.4 on 2025-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_about_me', '0009_message_is_read_message_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-29T10:30:00'),
            preserve_default=False,
        ),
    ]
